version: '3.2'

services:

   postgresql:
      image: "postgres:10.0"
      ports:
         - "5432:5432"
      volumes:
         - type: bind
           source: /Users/dave/src/apache-roller/deployment/docker-compose/postgresql-data
           target: /var/lib/postgresql/data
      environment:
         - POSTGRES_DB=rollerdb
         - POSTGRES_USER=scott
         - POSTGRES_PASSWORD=tiger

   roller:
      image: "roller:6.0.0-SNAPSHOT"
      ports:
         - "8080:8080"
      volumes:
         - type: bind
           source: /Users/dave/src/apache-roller/deployment/docker-compose/roller-data
           target: /var/lib/roller/data

